### ISSUE TITLE
How do I create the docker-layer-extract binary?

### ISSUE THREAD

**Issue by bob-ashforth-sp** [micahyoung/docker-layer-extract#2]

**Comment by micahyoung** [comment]
Good question! I'll update the docs but...

Since I don't have a GitHub release system setup, you'll need to `go build` it:

```bash
docker run --rm -v $PWD:/out -e GOBIN=/out golang go install github.com/micahyoung/docker-layer-extract@latest
```

That will output the `docker-layer-extract` binary to your current directory, hopefully building the right one for whatever OS you're on.

**Comment by bob-ashforth-sp** [comment]
> Good question! I'll update the docs but...
> 
> Since I don't have a GitHub release system setup, you'll need to `go build` it:
> 
> ```shell
> docker run --rm -v $PWD:/out -e GOBIN=/out golang go install github.com/micahyoung/docker-layer-extract@latest
> ```
> 
> That will output the `docker-layer-extract` binary to your current directory, hopefully building the right one for whatever OS you're on.

Thanks, Micah!
